### ISSUE TITLE
Possibility to use dates from post meta

### ISSUE THREAD

**Issue by emzo** [GaryJones/wp-calendar-core#1]
Looks like you're thinking of this already, but just to add my backing to this idea. For custom post types (think event post types for example) it would be useful if the posts could appear in the calendar based on a date value pulled from a custom field (post meta). I expect the post_date field to be the default date used for deciding where to display the post on the calendar, but it would be great to have some way of changing this.

I've often thought this should be the way a calendar should work. Many different plugins could utilise such a calendar for their own needs. Event plugins could be made much simpler by omitting the calendar component and hooking into this one - they would simply need to focus on defining a new post_type with custom fields for certain meta data.

Big thumbs up for this :thumbsup:, and I'd love to help out wherever possible.

**Comment by emzo** [comment]
I can see this would be easily implemented by subclassing. Excellent work so far. Looking forward to making use of this.

**Comment by GaryJones** [comment]
As per the README, the idea is that the classes created will be agnostic of the data being fed into them to display as a calendar, the same as `WP_Lists_Table` is. The classes provide the markup, and you create a subclass that provides the data.

For instance, the current 0.1.0 version has a `get_days_with_data()` method - which happens to look up post dates to match existing functionality, but if you wanted to look up values from a post meta field on a CPT, or user's activity (or new birthday field), etc., then that's fine - the classes just wants to know which days in that month it needs to do something different with (and what it does with it is also up to you - display a link and title, add a class to highlight, etc.).
